In [10]:
import numpy as np

In [11]:
print("Hello, World!")

Hello, World!

In [12]:
arr25=np.array([[10,-27,0,30],[20,0,0,40],[30,0,0,50],[40,0,0,60],[50,0,0,70]])
arr25

array([[ 10, -27,   0,  30],
       [ 20,   0,   0,  40],
       [ 30,   0,   0,  50],
       [ 40,   0,   0,  60],
       [ 50,   0,   0,  70]])

In [13]:
A=np.split(arr25, [1,3], axis=0)
A

[array([[ 10, -27,   0,  30]]),
 array([[20,  0,  0, 40],
        [30,  0,  0, 50]]),
 array([[40,  0,  0, 60],
        [50,  0,  0, 70]])]

In [14]:
B=np.split(arr25, [1,3], axis=1)
B

[array([[10],
        [20],
        [30],
        [40],
        [50]]),
 array([[-27,   0],
        [  0,   0],
        [  0,   0],
        [  0,   0],
        [  0,   0]]),
 array([[30],
        [40],
        [50],
        [60],
        [70]])]

In [15]:


np.ptp(arr25, axis=0)

array([40, 27,  0, 40])

In [16]:
arr100=np.arange(1,101).reshape(10,10)
arr100

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [17]:
np.save('saved_data',arr100)

In [18]:
np.savetxt('saved_data.txt',arr100)

In [19]:
np.loadtxt('saved_data.txt')

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [21]:
import pandas as pd

In [22]:
S=pd.Series([13,-54,36,8])
S

0    13
1   -54
2    36
3     8
dtype: int64

In [23]:
S2=pd.Series([12,43,54,78],index=['a','b','c','d'])
S2

a    12
b    43
c    54
d    78
dtype: int64

In [25]:
S.values

array([ 13, -54,  36,   8])

In [26]:
S.index

RangeIndex(start=0, stop=4, step=1)

In [27]:
S[1:3]

1   -54
2    36
dtype: int64

In [28]:
S2[1:5]

b    43
c    54
d    78
dtype: int64

In [31]:
S2['a':'d'].values

array([12, 43, 54, 78])

In [32]:
S2[['a','b','c']]

a    12
b    43
c    54
dtype: int64

In [34]:
S2['a']

np.int64(12)

In [35]:
S[1]=9
S

0    13
1     9
2    36
3     8
dtype: int64

In [ ]:
S3=pd.Series(S2)#create series from series
S3

a    12
b    43
c    54
d    78
dtype: int64

In [ ]:
arr=np.array([1,2,3,4])
S4=pd.Series(arr)#create series from array(Only 1D array can createb series)
S4

0    1
1    2
2    3
3    4
dtype: int64

In [41]:
S.isin([23])

0    False
1    False
2    False
3    False
dtype: bool

In [42]:
S.isnull()

0    False
1    False
2    False
3    False
dtype: bool

*DataFrame*

In [47]:
df=pd.DataFrame({
    'Name':['Amit'],
    'Age':[23]
}
)
df

   Name  Age
0  Amit   23

In [49]:
data={'Name':['Amit'],
      'Age':[23],
      'No':[12346789]}
df2=pd.DataFrame(data)
df2

   Name  Age        No
0  Amit   23  12346789

In [53]:
df3=pd.DataFrame(df2,columns=['Name','Age'])#dataframe from  anoter dataframe
df3

   Name  Age
0  Amit   23

In [55]:
df3=pd.DataFrame(df2,index=['a'])
df3

  Name  Age  No
a  NaN  NaN NaN

In [56]:
df2.index

RangeIndex(start=0, stop=1, step=1)

In [58]:
df3.Age

a   NaN
Name: Age, dtype: float64

In [59]:
#multiple columns
df.loc[0:2]

   Name  Age
0  Amit   23

In [61]:
df['Name'][0]

'Amit'

In [64]:
df[0:2][0:3]

   Name  Age
0  Amit   23

In [69]:
df.loc[0:2, ['Name', 'Age']]

   Name  Age
0  Amit   23

In [70]:
df['Email']='amit@'
df

   Name  Age  Email
0  Amit   23  amit@

In [73]:
df['Name']=['A']
df

  Name  Age  Email
0    A   23  amit@